// // const userInput = [0,1,2,3,4,5,6,7,8,9,10];

// // let answer = math.rand


// // function getRandomArbitrary(min, max) {
// //     return Math.random() * (10 - 0) + 0;
// //   }

// // if the input number is equal to the math.random number then alert you win, else, write higher or lower



// // program where the user has to guess a number generated by a program

// function guessNumber() {

//     // generating a random integer from 1 to 10
//     const random = Math.floor(Math.random() * 10) + 1;

//     // take input from the user
//     let number = parseInt(('Guess a number from 1 to 10: '));

//     // take the input until the guess is correct
//     while(number !== random) {
//         number = parseInt(('Guess a number from 1 to 10: '));
//     }

//     // check if the guess is correct
//     if(number === random) {
//         console.log('You guessed the correct number.');
//     }

// }

// // call the function
// guessNumber();

